site_name: Leading Edge Simulations <br>C-23 Sundowner v2.5.0
site_url: https://airfightergr.github.io/les_c23_docs/

nav:
  - Welcome:
    - Overview: index.md
    - Aircraft Characteristics: characteristics.md
    - User Interface: gui.md
    #- Controls Setup: commands.md
    - Support: support.md
  - 'Select Aircraft':
    - C23 Original: docs/c23/c23.md
    - C23 G1000: docs/c23_G1000/c23_G1000.md
    - C23 G5: docs/c23_G5/c23_G5.md
    - C23 G500: docs/c23_G500/c23_G500.md


theme:
    name: readthedocs

    #mkdocs, readthedocs, bootstrap,
  #            cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen,
  #            lux, materia, minty, pulse, sandstone, simplex, slate, solar,
  #            spacelab, superhero, united, yeti

markdown_extensions:
  - admonition
  - tables

plugins:
  - mkdocs-video
